spring.application.name=SecureAPK-Analyzer

spring.datasource.url=jdbc:h2:file:./data/secureapkdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8080
server.error.include-message=always

logging.level.com.secure.analyzer=DEBUG
logging.level.org.springframework.web=INFO